```{r}
install.packages("shiny")
install.packages("xml2")
install.packages("dplyr")
install.packages("DT")
```

```{r}
library(shiny)
library(xml2)
library(dplyr)
library(DT)

# Fonction pour extraire les votes d'un fichier XML
extract_votes <- function(file) {
  xml_data <- read_xml(file)
  
  dateScrutin <- xml_text(xml_find_first(xml_data, ".//dateScrutin"))
  libelle <- xml_text(xml_find_first(xml_data, ".//titre"))
  votes <- data.frame(dateScrutin = character(), libelle = character(), acteurRef = character(), vote = character(), stringsAsFactors = FALSE)
  
  groupes <- xml_find_all(xml_data, ".//groupe")
  
  for (groupe in groupes) {
    # Pour votes
    pour_votants <- xml_find_all(groupe, ".//decompteNominatif/pours/votant")
    if (length(pour_votants) > 0) {
      pour_votants_df <- data.frame(
        dateScrutin = rep(dateScrutin, length(pour_votants)),
        libelle = rep(libelle, length(pour_votants)),
        acteurRef = xml_text(xml_find_all(pour_votants, ".//acteurRef")),
        vote = rep("Pour", length(pour_votants)),
        stringsAsFactors = FALSE
      )
      votes <- rbind(votes, pour_votants_df)
    }
    
    # Contre votes
    contre_votants <- xml_find_all(groupe, ".//decompteNominatif/contres/votant")
    if (length(contre_votants) > 0) {
      contre_votants_df <- data.frame(
        dateScrutin = rep(dateScrutin, length(contre_votants)),
        libelle = rep(libelle, length(contre_votants)),
        acteurRef = xml_text(xml_find_all(contre_votants, ".//acteurRef")),
        vote = rep("Contre", length(contre_votants)),
        stringsAsFactors = FALSE
      )
      votes <- rbind(votes, contre_votants_df)
    }
    
    # Abstention votes
    abstention_votants <- xml_find_all(groupe, ".//decompteNominatif/abstentions/votant")
    if (length(abstention_votants) > 0) {
      abstention_votants_df <- data.frame(
        dateScrutin = rep(dateScrutin, length(abstention_votants)),
        libelle = rep(libelle, length(abstention_votants)),
        acteurRef = xml_text(xml_find_all(abstention_votants, ".//acteurRef")),
        vote = rep("Abstention", length(abstention_votants)),
        stringsAsFactors = FALSE
      )
      votes <- rbind(votes, abstention_votants_df)
    }
    
    # Non votants
    non_votants <- xml_find_all(groupe, ".//decompteNominatif/nonVotants/votant")
    if (length(non_votants) > 0) {
      non_votants_df <- data.frame(
        dateScrutin = rep(dateScrutin, length(non_votants)),
        libelle = rep(libelle, length(non_votants)),
        acteurRef = xml_text(xml_find_all(non_votants, ".//acteurRef")),
        vote = rep("Non Votant", length(non_votants)),
        stringsAsFactors = FALSE
      )
      votes <- rbind(votes, non_votants_df)
    }
  }
  
  return(votes)
}

# Définir l'interface utilisateur
ui <- fluidPage(
  titlePanel("Votes d'un Député"),
  sidebarLayout(
    sidebarPanel(
      textInput("acteurRef", "Référence de l'acteur:", ""),
      actionButton("search", "Rechercher"),
      downloadButton("downloadData", "Télécharger les données")
    ),
    mainPanel(
      DTOutput("votesTable")
    )
  )
)

# Définir le serveur
server <- function(input, output) {
  votesData <- eventReactive(input$search, {
    files <- list.files(path = "~/Desktop/shiny_deputes/xml/", pattern = "*.xml", full.names = TRUE)
    votes_list <- lapply(files, function(file) {
      tryCatch({
        extract_votes(file)
      }, error = function(e) {
        message(paste("Erreur dans le fichier :", file))
        message(e)
        return(data.frame(dateScrutin = character(), libelle = character(), acteurRef = character(), vote = character(), stringsAsFactors = FALSE))
      })
    })
    votes <- do.call(rbind, votes_list)
    votes <- votes %>% filter(acteurRef == input$acteurRef)
    return(votes)
  })

  output$votesTable <- renderDT({
    votesData()
  })

  output$downloadData <- downloadHandler(
    filename = function() {
      paste("votes_", Sys.Date(), ".csv", sep = "")
    },
    content = function(file) {
      write.csv(votesData(), file, row.names = FALSE)
    }
  )
}

shinyApp(ui = ui, server = server)
```

